# Generated by Django 2.2.11 on 2020-04-12 08:26

import PPECompliance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('pk_image', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=PPECompliance.models.user_directory_path)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagesProperties',
            fields=[
                ('pk_image_property', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'images_properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagesPropertiesTypes',
            fields=[
                ('pk_image_property_type', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'images_properties_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('pk_model', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'models',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelsProperties',
            fields=[
                ('pk_sn_model_property', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'models_properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelsPropertiesTypes',
            fields=[
                ('pk_model_property_type', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'models_properties_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PPEComplianceProperties',
            fields=[
                ('pk_ppe_compliance_property', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ppe_compliances_properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PPECompliances',
            fields=[
                ('pk_ppe_compliance', models.AutoField(primary_key=True, serialize=False)),
                ('result_image', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ppe_compliances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('pk_user', models.AutoField(primary_key=True, serialize=False)),
                ('customer_uid', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
